--- # Install Java

- hosts: jenkins2
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: "Install java"
    yum:
      name: java-1.8.0-openjdk
      state: latest
  - name: "Get RPM Key for Jenkins"
    rpm_key:
      state: present
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  - name: "Add Jenkins Repo"
    yum_repository:
      name: jenkins
      description: "Jenkins Repository"
      baseurl: http://pkg.jenkins.io/redhat
      gpgcheck: yes
  - name: "Install jenkins"
    yum: 
      name: jenkins
      state: latest
    notify: startservice
  handlers:
  - name: startservice
    service:
      name: jenkins
      state: restarted

